= prc-tools-remix

image:https://travis-ci.org/jichu4n/prc-tools-remix.svg?branch=master["Build Status", link="https://travis-ci.org/jichu4n/prc-tools-remix"]

== Overview

This repository is an archive of http://prc-tools.sourceforge.net/[prc-tools]
2.3 (and its GCC cross-compilation toolchain), with patches enabling it to build
and run on modern Linux and macOS systems.

http://prc-tools.sourceforge.net/[prc-tools] is a collection of tools supporting
C and C++ programming for Palm OS. It supplies a full GCC cross-compilation
toolchain for https://en.wikipedia.org/wiki/Motorola_68000_series[m68k] and
https://en.wikipedia.org/wiki/ARM_architecture[ARM], as well as Palm OS-specific
utilities.

As the Palm OS platform faded into oblivion, prc-tools appears to be have been
unmaintained since 2003 and no longer compiles under recent versions of GCC and
Clang. This repo includes a number of patches to enable it to build and run on
modern Linux and macOS systems.

== Installation

=== Debian / Ubuntu

If you're using a recent 64-bit version of Ubuntu or Debian, you can download
and install pre-built `.deb` packages for prc-tools-remix from the
https://github.com/jichu4n/prc-tools-remix/releases[Releases page].

Otherwise, please see "Building from source" below.

=== Arch Linux / Manjaro

You can install prc-tools-remix from the AUR:

```
yay -S prc-tools-remix
```

=== Building from source

See
https://github.com/jichu4n/prc-tools-remix/blob/master/tools/build.sh[`tools/build.sh`]
for general build steps.

To build and install using
https://github.com/jichu4n/prc-tools-remix/blob/master/tools/build.sh[`tools/build.sh`]:

[source,bash]
----
# Install dependencies:
sudo apt-get install \
    build-essential autoconf automake \
    libncurses-dev \
    flex bison \
    texinfo gperf

# Download code
git clone https://github.com/jichu4n/prc-tools-remix.git
cd prc-tools-remix

# Build and install into "./dist/" directory.
./tools/build.sh

# To build a binary tarball:
(cd ./dist && tar cvjf ../prc-tools-remix.tar.bz2 *)
# To unpack into your system:
sudo tar xvjf prc-tools-remix.tar.bz2 -c /
----

== Usage

Please refer to the http://prc-tools.sourceforge.net/[prc-tools homepage] for
documentation on usage.
