prc-tools-remix
~~~~~~~~~~~~~~~

image:https://travis-ci.org/jichu4n/prc-tools-remix.svg?branch=master["Build Status", link="https://travis-ci.org/jichu4n/prc-tools-remix"]

Overview
^^^^^^^^

This repository is an archive of http://prc-tools.sourceforge.net/[prc-tools]
2.3 (and its GCC cross-compilation toolchain), with patches enabling it to build
and run on modern Linux and macOS systems.

http://prc-tools.sourceforge.net/[prc-tools] is a collection of tools supporting
C and C++ programming for Palm OS. It supplies a full GCC cross-compilation
toolchain for https://en.wikipedia.org/wiki/Motorola_68000_series[m68k] and
https://en.wikipedia.org/wiki/ARM_architecture[ARM], as well as Palm OS-specific
utilities.

As the Palm OS platform faded into oblivion, prc-tools appears to be have been
unmaintained since 2003 and no longer compiles under recent versions of GCC and
Clang. This repo includes a number of patches to enable it to build and run on
modern Linux and macOS systems.

Building
^^^^^^^^

Linux
+++++

To build from source on Linux, e.g., on Ubuntu:

[source,bash]
----
sudo apt-get install \
    build-essential autoconf automake \
    libncurses-dev \
    flex bison \
    texinfo gperf

git clone https://github.com/jichu4n/prc-tools-remix.git
cd prc-tools-remix

mkdir build && cd build
../prc-tools-2.3/configure \
    --enable-targets=m68k-palmos,arm-palmos \
    --enable-languages=c,c++ \
    --disable-nls \
    --build=i686-linux-gnu \
    --host=i686-linux-gnu \
    --prefix=/usr \
    --with-palmdev-prefix=/opt/palmdev
# Use "env SHELL=/bin/sh make" if using a non-POSIX shell like fish
make
sudo make MAKEINFO=true install
----

macOS
+++++

On macOS, you can install using http://brew.sh[Homebrew] with:

[source,bash]
----
brew tap jichu4n/palm-os
brew install prc-tools
----

See the Homebrew tap
https://github.com/jichu4n/homebrew-palm-os[jichu4n/palm-os] for details.

To build from source on macOS, assuming you have a sane build environment
from http://brew.sh[Homebrew] / Xcode:

[source,bash]
----
git clone https://github.com/jichu4n/prc-tools-remix.git
cd prc-tools-remix

mkdir build && cd build
../prc-tools-2.3/configure \
    --enable-targets=m68k-palmos,arm-palmos \
    --enable-languages=c,c++ \
    --disable-nls \
    --build=i686-apple-darwin \
    --host=i686-apple-darwin \
    --with-palmdev-prefix=/usr/local/opt/palmdev
# Use "env SHELL=/bin/sh make" if using a non-POSIX shell like fish
make
make MAKEINFO=true install
----

Usage
^^^^^

Please refer to the http://prc-tools.sourceforge.net/[prc-tools homepage] for
documentation on usage.
