= prc-tools-remix

image:https://github.com/jichu4n/prc-tools-remix/actions/workflows/build.yaml/badge.svg["Build", link="https://github.com/jichu4n/prc-tools-remix/actions/workflows/build.yaml"]
image:https://github.com/jichu4n/prc-tools-remix/actions/workflows/setup-palm-os-dev-env.yaml/badge.svg["Dev env setup", link="https://github.com/jichu4n/prc-tools-remix/actions/workflows/setup-palm-os-dev-env.yaml"]

== Overview

This repository is an archive of http://prc-tools.sourceforge.net/[prc-tools]
2.3 and its GCC cross-compilation toolchain, with patches enabling it to build
and run on modern Linux and macOS systems.

http://prc-tools.sourceforge.net/[prc-tools] is a collection of tools supporting
C and C++ programming for Palm OS. It supplies a full GCC cross-compilation
toolchain for https://en.wikipedia.org/wiki/Motorola_68000_series[m68k] and
https://en.wikipedia.org/wiki/ARM_architecture[ARM], as well as Palm OS-specific
utilities.

As the Palm OS platform faded into oblivion, prc-tools appears to be have been
unmaintained since 2003 and no longer compiles under recent versions of GCC and
Clang. This repo includes a number of patches to enable it to build and run on
modern Linux and macOS systems.

== Installation

=== Debian / Ubuntu

If you're using a recent 64-bit version of Ubuntu or Debian, you can download
and install pre-built `.deb` packages for prc-tools-remix from the
https://github.com/jichu4n/prc-tools-remix/releases[Releases page].

For a full Palm OS development environment that includes
https://github.com/jichu4n/prc-tools-remix[prc-tools-remix],
https://github.com/jichu4n/palm-os-sdk[Palm OS SDKs] and
https://github.com/jichu4n/pilrc[PilRC], you can use the one-click install script
https://github.com/jichu4n/prc-tools-remix/blob/master/tools/setup-palm-os-dev-env.sh[`tools/setup-palm-os-dev-env.sh`]:

[source,bash]
----
curl -sLO https://github.com/jichu4n/prc-tools-remix/raw/master/tools/setup-palm-os-dev-env.sh
bash ./setup-palm-os-dev-env.sh $DIST
----
...where `$DIST` can be one of `focal`, `bionic`, `xenial`, `buster`, or
`stretch`, depending on your distro and version.

Otherwise, please see "Building from source" below.

=== Arch Linux / Manjaro

You can install prc-tools-remix from the AUR:

[source,bash]
----
yay -S prc-tools-remix
----

For a full Palm OS development environment that includes
https://github.com/jichu4n/prc-tools-remix[prc-tools-remix],
https://github.com/jichu4n/palm-os-sdk[Palm OS SDKs] and
https://github.com/jichu4n/pilrc[PilRC]:

[source,bash]
----
yay -S prc-tools-remix palm-os-sdk-git pilrc
----


=== Building from source

See
https://github.com/jichu4n/prc-tools-remix/blob/master/tools/build.sh[`tools/build.sh`]
for general build steps.

==== Linux

To build and install using
https://github.com/jichu4n/prc-tools-remix/blob/master/tools/build.sh[`tools/build.sh`]:

[source,bash]
----
# Install dependencies:
sudo apt-get install \
    build-essential autoconf automake \
    libncurses-dev \
    flex bison \
    texinfo gperf

# Download code:
git clone https://github.com/jichu4n/prc-tools-remix.git
cd prc-tools-remix

# Build and install into "./dist/" directory:
./tools/build.sh

# To build a binary tarball:
(cd ./dist && tar cvjf ../prc-tools-remix.tar.bz2 *)
# To unpack into your system:
sudo tar xvjf prc-tools-remix.tar.bz2 -C /
----

==== macOS 13+ (including Apple Silicon / ARM)

For macOS systems, including Apple Silicon Macs (M1/M2/M3):

[source,bash]
----
# Install dependencies using Homebrew:
brew install texinfo autoconf automake gperf

# Ensure Xcode Command Line Tools are installed:
xcode-select --install

# Download code:
git clone https://github.com/jichu4n/prc-tools-remix.git
cd prc-tools-remix

# Build and install into "./dist/" directory:
./tools/build-macos.sh

# To install into your system:
sudo cp -R ./dist/usr/local/* /usr/local/
----

For a full Palm OS development environment, you'll also need the following:

- https://github.com/jichu4n/palm-os-sdk[Palm OS SDKs]: See https://github.com/jichu4n/prc-tools-remix/blob/master/tools/setup-palm-os-sdk.sh[`tools/setup-palm-os-sdk.sh`]
- https://github.com/jichu4n/pilrc[PilRC]: Install pre-built `deb` packages from the https://github.com/jichu4n/pilrc/releases/[Releases page], or see https://github.com/jichu4n/pilrc/blob/master/tools/build-deb.sh[PilRC build script] for general build steps


== Usage

Please refer to the http://prc-tools.sourceforge.net/[prc-tools homepage] for
documentation on usage.

