.TH BUILD-PRC 1 "PalmOS Pilot tools" "Contrib to FSF" \" -*- nroff -*-
.SH NAME
build-prc \- Bind
.B PalmOS
compatible binary resources into a
.B PalmOS .prc
"executable" file
.SH SYNOPSIS
.B build-prc fname.prc 'App Name' apid resource resource ...
.SH DESCRIPTION
This manual page
documents the utility
.BR build-prc .
.B build-prc
reads any number of binary
.B PalmOS
resources in seperate files and binds them together into a
.B .prc
file with the name, application name and application ID as specified on the 
command line.
.SS OPTIONS
.TP
-l generate a GNU style 'GLib' shared library
.TP
-L generate a PalmOS version 2 style shared library
.SH BUGS
.B build-prc
still uses constant 'magic' values for some fields that have known contents.
.SH AUTHOR
.B build-prc
was written by D.Jeff Dionne
