.TH TXT2BITM 1 "PalmOS Pilot tools" "Thruput Data Systems" \" -*- nroff -*-
.SH NAME
txt2bitm \- Convert a text file into
.B PalmOS
compatible binary icon resource.
.SH SYNOPSIS
.B txt2bitm -I<resource ID> -T<resource Type> input_file_name
.SH DESCRIPTION
This manual page
documents the utility
.BR txt2bitm .
.B txt2bitm
reads a text file given on the command line and writes a
.B PalmOS
compatible binary resource file with the resource ID and type as specified
on the command line.
.SS OPTIONS
.BR -I<resource ID>
specifies the resource ID number to use for this bitmap.  If not given,
defaults to decimal 1000.
.BR -T<resource Type>
specifies the resource type to use for this bitmap.  If not given, defaults
to tAIB.
.SH BUGS
No known bugs
.SH AUTHOR
.B txt2bitm
was written by Andy Sackheim and is Copyright 1996 Thruput Data Systems, Inc.
This man page written by D.Jeff Dionne.
