/* DO NOT EDIT!
   This file was automatically generated by @progname@
   from @deffile@  */

	.file	"@fname@"

	@-variables-@

.text
	.globl	_GccRelocateData
_GccRelocateData:
	bra.w	_GccLoadCodeAndRelocateData

.section ehook
	.long	_GccReleaseCode
