/* DO NOT EDIT!  This file is generated by GenBootstrap; any modifications
   should be made to that program's source code instead.

   The contents of this file are in the public domain.  */

#ifndef BOOTSTRAP_UI_H
#define BOOTSTRAP_UI_H

/* Font Manager */

enum {stdFont = 0};

UInt8 FntSetFont (UInt8)  TRAP (0xA164);

/* Rectangles */

typedef struct {
  Int16 x;
  Int16 y;
  } PointType;

typedef struct {
  PointType topLeft;
  PointType extent;
  } RectangleType;

/* Window Manager */

enum {winUp = 0};

void WinScrollRectangle (const RectangleType*, UInt8, Int16, RectangleType*)  TRAP (0xA20A);
void WinEraseRectangle (const RectangleType*, UInt16)  TRAP (0xA219);
void WinDrawChars (const char*, Int16, Int16, Int16)  TRAP (0xA220);

#endif
